/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ContactSubmission = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const TestRequest = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'testItemType' : IDL.Text,
  'standards' : IDL.Opt(IDL.Text),
  'submittedAt' : IDL.Int,
  'email' : IDL.Opt(IDL.Text),
  'company' : IDL.Opt(IDL.Text),
  'message' : IDL.Opt(IDL.Text),
  'preferredDate' : IDL.Opt(IDL.Int),
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteContactSubmission' : IDL.Func([IDL.Text], [], []),
  'deleteTestRequest' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactSubmissionById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ContactSubmission)],
      ['query'],
    ),
  'getContactSubmissions' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getTestRequestById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(TestRequest)],
      ['query'],
    ),
  'getTestRequests' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(TestRequest)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
      [IDL.Text],
      [],
    ),
  'submitTestRequest' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Int),
      ],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ContactSubmission = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const TestRequest = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'testItemType' : IDL.Text,
    'standards' : IDL.Opt(IDL.Text),
    'submittedAt' : IDL.Int,
    'email' : IDL.Opt(IDL.Text),
    'company' : IDL.Opt(IDL.Text),
    'message' : IDL.Opt(IDL.Text),
    'preferredDate' : IDL.Opt(IDL.Int),
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteContactSubmission' : IDL.Func([IDL.Text], [], []),
    'deleteTestRequest' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactSubmissionById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ContactSubmission)],
        ['query'],
      ),
    'getContactSubmissions' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getTestRequestById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(TestRequest)],
        ['query'],
      ),
    'getTestRequests' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(TestRequest)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
        [IDL.Text],
        [],
      ),
    'submitTestRequest' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Int),
        ],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };